import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
const bundle=await build({entryPoints:['entry/src/main/ets/domain/SessionStore.ets'],bundle:true,write:false,format:'esm',platform:'node',loader:{'.ets':'ts'},resolveExtensions:['.ets','.ts','.js']});
const {SessionStore}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const pb=await build({entryPoints:['entry/src/main/ets/domain/PolicyEngine.ets'],bundle:true,write:false,format:'esm',platform:'node',loader:{'.ets':'ts'},resolveExtensions:['.ets','.ts','.js']});
const {PolicyEngine}=await import('data:text/javascript;base64,'+Buffer.from(pb.outputFiles[0].text).toString('base64'));
function session(){const s=new SessionStore();s.regions=[{regionId:'lip',assetId:s.assetId,assetVersion:s.assetVersion,width:1024,height:1024,semantic:'confirmed-lips',fileName:'lip.mask'}];return s;}
function commit(s:any){s.succeeded(s.pendingRequest,s.revision);}
test('candidate and authorized-pending are not successful history',()=>{const s=session(),p=s.propose('lipTint','lip');assert.equal(s.operations.length,0);s.authorize(p.planId);assert.equal(s.operations.length,0);assert.equal(s.snapshots.length,1);commit(s);assert.equal(s.operations.length,1);});
test('forged/cancelled authorization and concurrent execution rejected',()=>{const s=session();assert.throws(()=>s.authorize('fake'));const p=s.propose('lipTint','lip');s.authorize(p.planId);assert.throws(()=>s.authorize(p.planId));s.failed();assert.equal(s.operations.length,0);});
test('only latest candidate can be authorized',()=>{const s=session(),a=s.propose('lipTint','lip'),b=s.propose('lipTint','lip');assert.throws(()=>s.authorize(a.planId));s.authorize(b.planId);});
test('stale and mismatched rendering acknowledgements cannot commit',()=>{const s=session(),p=s.propose('lipTint','lip');s.authorize(p.planId);assert.equal(s.succeeded('old',s.revision),false);assert.equal(s.succeeded(s.pendingRequest,0),false);assert.equal(s.operations.length,0);commit(s);});
for(const strength of [NaN,Infinity,-.1,.66])test(`strength ${strength} rejected`,()=>assert.throws(()=>session().propose('lipTint','lip','rose',strength)));
test('unknown operation, region and preset rejected',()=>{const s=session();assert.throws(()=>s.propose('smoothSkin','lip'));assert.throws(()=>s.propose('lipTint','foreign'));assert.throws(()=>s.propose('lipTint','lip','SKU-magic'));});
test('photo regions do not magically become lips',()=>{const s=session();s.sourceKind='PHOTO';assert.throws(()=>s.propose('lipTint','lip'));assert.doesNotThrow(()=>s.propose('localTint','lip'));});
test('undo redo acknowledged only after successful replay',()=>{const s=session();s.authorize(s.propose('lipTint','lip').planId);commit(s);s.replay(-1);assert.equal(s.operations.length,1);commit(s);assert.equal(s.operations.length,0);s.replay(1);commit(s);assert.equal(s.operations.length,1);});
test('absolute adjustment replaces previous operation',()=>{const s=session();s.authorize(s.propose('lipTint','lip').planId);commit(s);s.authorize(s.propose('lipTint','lip','rose',.1,true).planId);commit(s);assert.equal(s.operations.length,1);assert.equal(s.operations[0].absoluteStrength,.1);});
test('current-result protection retains immutable snapshot through adjustment / reopen',()=>{const s=session();s.authorize(s.propose('lipTint','lip').planId);commit(s);s.protect('lip',true,false);s.authorize(s.propose('lipTint','lip','rose',.6,true).planId);commit(s);assert.equal(s.protection.anchorOperations[0].absoluteStrength,.25);const saved=s.serialize('work-1','test');const reopened=session();reopened.restore(saved);assert.equal(reopened.protection.anchorOperations[0].absoluteStrength,.25);assert.equal(reopened.operations[0].absoluteStrength,.6);});
test('original protection is not confused with current result',()=>{const s=session();s.authorize(s.propose('lipTint','lip').planId);commit(s);s.protect('lip',false,false);assert.equal(s.protection.anchorOperations.length,0);assert.equal(s.protection.anchorRevision,0);});
test('pending preview cannot be saved',()=>{const s=session();s.authorize(s.propose('lipTint','lip').planId);assert.throws(()=>s.serialize('work-1','pending'));});
test('un-calibrated brand products cannot simulate',()=>{assert.equal(PolicyEngine.productSimulationAllowed('', ['brand-information']),false);assert.equal(PolicyEngine.productSimulationAllowed('', ['calibrated-simulation']),false);});
test('saved view retains selected angle without modifying edit operations',()=>{const s=session();s.view={yaw:.57,pitch:.08,distance:18,panX:0,panY:0};const restored=session();restored.restore(s.serialize('work-1','angled'));assert.deepEqual(restored.view,s.view);assert.equal(restored.operations.length,0);});
const ambientBundle=await build({entryPoints:['entry/src/main/ets/services/AmbiencePreference.ets'],bundle:true,write:false,format:'esm',platform:'node',loader:{'.ets':'ts'},resolveExtensions:['.ets','.ts','.js']});
const {AmbiencePreference}=await import('data:text/javascript;base64,'+Buffer.from(ambientBundle.outputFiles[0].text).toString('base64'));
test('ambience responds to explicit statements, handles negation, leaves unrelated chat unchanged',()=>{assert.equal(AmbiencePreference.fromText('我今天很开心'),'warm');assert.equal(AmbiencePreference.fromText('我不开心'),'quiet');assert.equal(AmbiencePreference.fromText('我有点累'),'quiet');assert.equal(AmbiencePreference.fromText('看看产品资料'),undefined);assert.equal(AmbiencePreference.fromText('这里有颗痣'),undefined);});
