"""Compile reviewed factual records. Does not crawl, infer formulas or invent calibration."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
catalog = json.loads((ROOT / 'shared/products/olay-cn-catalog.json').read_text(encoding='utf-8'))
fields = ['productId','brand','name','region','formulaVersion','specification','usageSummary','source',
          'retrievedAt','evidenceType','materialRights','allowedViews','calibrationProfile','illustration']
records = []
ids = set()
for p in catalog['records']:
    assert p['productId'] not in ids
    ids.add(p['productId'])
    assert p['market'] == 'CN-mainland' and p['inci'] is None and p['calibrationProfile'] == ''
    assert p['allowedViews'] == ['channel-information'] and p['availability'] == 'not-verified'
    assert (ROOT / 'entry/src/main/resources/rawfile/products' / p['illustration']).exists()
    records.append({f:p[f] for f in fields})
types = '\n'.join(f'  {f}: {"string[]" if f == "allowedViews" else "string"};' for f in fields)
code = '// Generated by scripts/build-product-catalog.py; edit the reviewed JSON source.\n'
code += f'export interface ProductRecord {{\n{types}\n}}\n'
code += 'export class ProductRepository {\n  static records():ProductRecord[] { return '
code += json.dumps(records,ensure_ascii=False,indent=2) + '; }\n'
code += '  static status():string { return '+json.dumps(catalog['coverageNote'],ensure_ascii=False)+'; }\n}\n'
(ROOT / 'entry/src/main/ets/services/ProductRepository.ets').write_text(code,encoding='utf-8')
print(f'Generated {len(records)} mainland channel records; zero calibrated product simulations.')
