#include "RendererSession.h"
#include "CameraPipeline.h"
#include <napi/native_api.h>
#include <arkui/native_node_napi.h>
#include <arkui/native_interface.h>
#include <ace/xcomponent/native_interface_xcomponent.h>
#include <map>
#include <memory>
#include <cstring>
using namespace self;
namespace {
struct Binding {std::shared_ptr<RendererSession> renderer;OH_ArkUI_SurfaceHolder* holder=nullptr;OH_ArkUI_SurfaceCallback* callback=nullptr;napi_threadsafe_function event=nullptr;bool attached=false;};
std::map<std::string,std::unique_ptr<Binding>> bindings;
std::string string(napi_env env,napi_value value){size_t size=0;napi_get_value_string_utf8(env,value,nullptr,0,&size);if(size>1024*1024)throw std::runtime_error("String budget");std::string result(size,'\0');napi_get_value_string_utf8(env,value,result.data(),size+1,&size);return result;}
napi_value text(napi_env env,const std::string& s){napi_value value;napi_create_string_utf8(env,s.c_str(),s.size(),&value);return value;}
Binding* binding(OH_ArkUI_SurfaceHolder* holder){return static_cast<Binding*>(OH_ArkUI_SurfaceHolder_GetUserData(holder));}
void created(OH_ArkUI_SurfaceHolder* holder){auto b=binding(holder);if(!b||b->attached)return;auto window=OH_ArkUI_XComponent_GetNativeWindow(holder);if(window){b->attached=true;try{b->renderer->attach(window);}catch(const std::exception&) {b->attached=false;}}}
void changed(OH_ArkUI_SurfaceHolder* holder,uint64_t w,uint64_t h){auto b=binding(holder);if(b)b->renderer->resize(w,h);}
void destroyed(OH_ArkUI_SurfaceHolder* holder){auto b=binding(holder);if(b&&b->attached){b->attached=false;b->renderer->detach();}}
void release(const std::string& id){auto it=bindings.find(id);if(it==bindings.end())return;auto& b=it->second;b->renderer->silenceEvents();OH_ArkUI_SurfaceHolder_RemoveSurfaceCallback(b->holder,b->callback);if(b->attached)b->renderer->detach();OH_ArkUI_SurfaceHolder_SetUserData(b->holder,nullptr);OH_ArkUI_SurfaceCallback_Dispose(b->callback);OH_ArkUI_SurfaceHolder_Dispose(b->holder);b->renderer.reset();napi_release_threadsafe_function(b->event,napi_tsfn_release);bindings.erase(it);}
void jsEvent(napi_env env,napi_value callback,void*,void* data){std::unique_ptr<std::string> value(static_cast<std::string*>(data));if(!env||!callback)return;napi_value global,result,arg=text(env,*value);napi_get_undefined(env,&global);napi_call_function(env,global,callback,1,&arg,&result);}
napi_value bind(napi_env env,napi_callback_info info){try{size_t argc=3;napi_value args[3];napi_get_cb_info(env,info,&argc,args,nullptr,nullptr);if(argc!=3)throw std::runtime_error("bind arguments");auto id=string(env,args[0]);release(id);if(!OH_ArkUI_QueryModuleInterfaceByName(ARKUI_NATIVE_NODE,"ArkUI_NativeNodeAPI_1"))throw std::runtime_error("Native node module initialization");ArkUI_NodeHandle node=nullptr;if(OH_ArkUI_GetNodeHandleFromNapiValue(env,args[1],&node)!=0||!node)throw std::runtime_error("FrameNode conversion");auto b=std::make_unique<Binding>();b->renderer=std::make_shared<RendererSession>();b->holder=OH_ArkUI_SurfaceHolder_Create(node);b->callback=OH_ArkUI_SurfaceCallback_Create();if(!b->holder||!b->callback)throw std::runtime_error("SurfaceHolder creation");napi_create_threadsafe_function(env,args[2],nullptr,text(env,"SELF events"),0,1,nullptr,nullptr,nullptr,jsEvent,&b->event);auto tsfn=b->event;b->renderer->event=[tsfn](const Json& event){auto* s=new std::string(event.dump());if(napi_call_threadsafe_function(tsfn,s,napi_tsfn_nonblocking)!=napi_ok)delete s;};OH_ArkUI_SurfaceHolder_SetUserData(b->holder,b.get());OH_ArkUI_SurfaceCallback_SetSurfaceCreatedEvent(b->callback,created);OH_ArkUI_SurfaceCallback_SetSurfaceChangedEvent(b->callback,changed);OH_ArkUI_SurfaceCallback_SetSurfaceDestroyedEvent(b->callback,destroyed);if(OH_ArkUI_SurfaceHolder_AddSurfaceCallback(b->holder,b->callback)!=0)throw std::runtime_error("Register surface callbacks");auto holder=b->holder;bindings[id]=std::move(b);created(holder);return nullptr;}catch(const std::exception& e){napi_throw_error(env,nullptr,e.what());return nullptr;}}
napi_value unbind(napi_env env,napi_callback_info info){size_t argc=1;napi_value args[1];napi_get_cb_info(env,info,&argc,args,nullptr,nullptr);if(argc)release(string(env,args[0]));return nullptr;}
struct Work {napi_async_work work=nullptr;napi_deferred deferred=nullptr;std::shared_ptr<RendererSession> renderer;Json request;std::vector<uint8_t> bytes;Result result;std::string error;bool camera=false;};
void execute(napi_env,void* ptr){auto* w=static_cast<Work*>(ptr);try{if(w->camera)w->result.data=cameraProcess(w->request,w->bytes);else w->result=w->renderer->process(std::move(w->request),std::move(w->bytes));}catch(const std::exception& e){w->error=e.what();}}
void complete(napi_env env,napi_status status,void* ptr){std::unique_ptr<Work> w(static_cast<Work*>(ptr));if(!w->error.empty()||status!=napi_ok){napi_value err;napi_create_error(env,nullptr,text(env,w->error.empty()?"Native work cancelled":w->error),&err);napi_reject_deferred(env,w->deferred,err);}else{napi_value obj;napi_create_object(env,&obj);napi_set_named_property(env,obj,"json",text(env,w->result.data.dump()));napi_value buffer;void* data;napi_create_arraybuffer(env,w->result.bytes.size(),&data,&buffer);if(!w->result.bytes.empty())std::memcpy(data,w->result.bytes.data(),w->result.bytes.size());napi_set_named_property(env,obj,"bytes",buffer);napi_resolve_deferred(env,w->deferred,obj);}napi_delete_async_work(env,w->work);}
napi_value request(napi_env env,napi_callback_info info){try{size_t argc=3;napi_value args[3];napi_get_cb_info(env,info,&argc,args,nullptr,nullptr);if(argc<2)throw std::runtime_error("Request arguments");auto it=bindings.find(string(env,args[0]));if(it==bindings.end())throw std::runtime_error("Native session not bound");auto json=Json::parse(string(env,args[1]));std::vector<uint8_t> bytes;if(argc==3){void* data=nullptr;size_t size=0;bool isBuffer=false;napi_is_arraybuffer(env,args[2],&isBuffer);if(!isBuffer)throw std::runtime_error("ArrayBuffer required");napi_get_arraybuffer_info(env,args[2],&data,&size);if(size>32*1024*1024)throw std::runtime_error("Byte budget exceeded");if(size)bytes.assign(static_cast<uint8_t*>(data),static_cast<uint8_t*>(data)+size);}auto w=std::make_unique<Work>();w->renderer=it->second->renderer;w->request=std::move(json);w->bytes=std::move(bytes);napi_value promise;napi_create_promise(env,&w->deferred,&promise);napi_create_async_work(env,nullptr,text(env,"SELF render command"),execute,complete,w.get(),&w->work);napi_queue_async_work(env,w->work);w.release();return promise;}catch(const std::exception& e){napi_throw_error(env,nullptr,e.what());return nullptr;}}
napi_value camera(napi_env env,napi_callback_info info){
 try{size_t argc=2;napi_value args[2];napi_get_cb_info(env,info,&argc,args,nullptr,nullptr);
 if(argc<1)throw std::runtime_error("Camera arguments");auto w=std::make_unique<Work>();w->camera=true;w->request=Json::parse(string(env,args[0]));
 if(argc==2){void* data=nullptr;size_t size=0;bool buffer=false;napi_is_arraybuffer(env,args[1],&buffer);if(!buffer)throw std::runtime_error("Camera ArrayBuffer required");napi_get_arraybuffer_info(env,args[1],&data,&size);if(size>1280*1280*4)throw std::runtime_error("Camera byte budget");if(size)w->bytes.assign(static_cast<uint8_t*>(data),static_cast<uint8_t*>(data)+size);}
 napi_value promise;napi_create_promise(env,&w->deferred,&promise);napi_create_async_work(env,nullptr,text(env,"SELF local camera"),execute,complete,w.get(),&w->work);napi_queue_async_work(env,w->work);w.release();return promise;
 }catch(const std::exception& e){napi_throw_error(env,nullptr,e.what());return nullptr;}
}
napi_value init(napi_env env,napi_value exports){napi_property_descriptor props[]={{"camera",nullptr,camera,nullptr,nullptr,nullptr,napi_default,nullptr},{"bind",nullptr,bind,nullptr,nullptr,nullptr,napi_default,nullptr},{"unbind",nullptr,unbind,nullptr,nullptr,nullptr,napi_default,nullptr},{"request",nullptr,request,nullptr,nullptr,nullptr,napi_default,nullptr}};napi_define_properties(env,exports,4,props);return exports;}
napi_module module={1,0,nullptr,init,"self_native",nullptr,{0}};
}
extern "C" __attribute__((constructor)) void RegisterSelf(){napi_module_register(&module);}



